server:
  port: 80
logging:
  level:
    root: info
    sun.rmi: error
    web: debug
    com:
      itsdcode:
        codingtest:
          yrseo: info
    org.hibernate:
      sql: debug
    com.zaxxer.hikari: info
    com.baroservice: trace
    com.sun.xml.ws.transport.http.client.HttpTransportPipe: debug
    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: debug
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
    org.hibernate.type.descriptor.sql.BasicExtractor: debug
spring:
  devtools:
    add-properties: false
  profiles: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/dcode_yrseo?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.mariadb.jdbc.Driver
    username: yrseo
    password: yrseo
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    hibernate:
      ddl-auto: create-drop
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    showSql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true