server:
  port: 80
logging:
  level:
    root: info
    sun.rmi: error
    web: info
    com:
      itsdcode:
        codingtest:
          yrseo: debug
    org.hibernate:
      sql: debug
    com.zaxxer.hikari: info
    javax.jws: trace
    org.springframework.ws.server.MessageTracing: trace
    org.springframework.ws: trace
    org.springframework.cache: trace
    com.sun.xml.ws.transport.http.client.HttpTransportPipe: debug
    org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: debug
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: debug
    org.hibernate.type.descriptor.sql.BasicExtractor: debug
spring:
  devtools:
    add-properties: false
  profiles: dev
  datasource:
    url: jdbc:h2:~/dcode;IGNORECASE=TRUE;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE;
    driver-class-name: org.h2.Driver
    username: sa
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
      data-source-properties:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    showSql: false
    show-sql: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true